[[libcxxwrap_julia]]
arch = "aarch64"
git-tree-sha1 = "ee60ba76cc9f36208ecaf9114b77b2b6b5b033de"
julia_version = "1.10.0"
os = "macos"

    [[libcxxwrap_julia.download]]
    sha256 = "745aa737d491de12a863cb89a5e46d5c790d01608301d0ecaaec65740365a5e2"
    url = "https://github.com/barche/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.12.17+0/libcxxwrap_julia.v0.12.17.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
