[[libcxxwrap_julia]]
arch = "aarch64"
git-tree-sha1 = "6ca3b47b57bbe2c120de2a65049218fc066de797"
julia_version = "1.10.0"
os = "macos"

    [[libcxxwrap_julia.download]]
    sha256 = "acc052721d39f184733743d90f9487b0e123f84d36d400fc47239ef78756a707"
    url = "https://github.com/barche/libcxxwrap_julia_jll.jl/releases/download/libcxxwrap_julia-v0.12.13+0/libcxxwrap_julia.v0.12.13.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
